import os
import sys
from typing import TypedDict, List, Optional

from dotenv import load_dotenv
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
from langchain.schema import HumanMessage
from langchain_community.tools.tavily_search import TavilySearchResults

# Load environment variables (TAVILY_API_KEY, OPENAI_API_KEY, etc.)
load_dotenv()

# ---------------------------------------------------------------------------
# State definition
# ---------------------------------------------------------------------------
class BriefState(TypedDict):
    """State used by the LangGraph agent.

    * ``topic`` вЂ“ the research topic supplied by the user.
    * ``outline`` вЂ“ list of outline items generated by the ``outline`` node.
    * ``step_index`` вЂ“ index of the current research step.
    * ``notes`` вЂ“ accumulated notes, one per outline item.
    * ``final_brief`` вЂ“ the synthesized brief produced at the end.
    """

    topic: str
    outline: Optional[List[str]]
    step_index: int
    notes: List[str]
    final_brief: Optional[str]

# ---------------------------------------------------------------------------
# Helper вЂ“ LLM client
# ---------------------------------------------------------------------------
def get_llm() -> ChatOpenAI:
    """Create a ChatOpenAI instance.

    The function checks that the ``OPENAI_API_KEY`` environment variable is set.
    If it is missing, a clear ``RuntimeError`` is raised.
    """
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY not found in environment. Please add it to .env or export it."
        )
    # Model can be changed via env var if desired.
    model_name = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
    return ChatOpenAI(model=model_name, temperature=0.2)

# ---------------------------------------------------------------------------
# Nodes
# ---------------------------------------------------------------------------
def outline_node(state: BriefState) -> dict:
    """Generate a 4вЂ‘5 item outline for the given ``topic``.

    The LLM is asked to return a JSONвЂ‘compatible list of short bullet points.
    """
    llm = get_llm()
    prompt = (
        f"You are an academic researcher. Create a concise outline (4вЂ‘5 bullet points) "
        f"that a student could use to write a short research brief about the following topic:"
        f"\n\n{state['topic']}\n\n"
        "Return ONLY a JSON list of strings, e.g. ['point 1', 'point 2', ...]."
    )
    response = llm.invoke([HumanMessage(content=prompt)])
    try:
        # The response content should be a JSON list; we evaluate safely.
        outline = eval(response.content, {"__builtins__": {}})  # noqa: S307
        if not isinstance(outline, list) or not all(isinstance(i, str) for i in outline):
            raise ValueError
    except Exception as exc:
        raise RuntimeError(
            f"Failed to parse outline from LLM response. Response was: {response.content}"
        ) from exc

    # Ensure we have 4вЂ‘5 items вЂ“ if not, truncate or pad with generic items.
    if len(outline) < 4:
        raise RuntimeError("Outline generated fewer than 4 items, which is unexpected.")
    if len(outline) > 5:
        outline = outline[:5]

    return {"outline": outline, "step_index": 0, "notes": []}


def research_step_node(state: BriefState) -> dict:
    """Perform a single webвЂ‘search for the current outline point and create a note.

    * One call to Tavily per step.
    * Summarise the top results (5вЂ‘8 sentences) using the LLM.
    """
    if state["outline"] is None:
        raise RuntimeError("Outline is missing вЂ“ the graph is in an invalid state.")
    if state["step_index"] >= len(state["outline"]):
        raise RuntimeError("step_index out of range вЂ“ no more outline items to research.")

    current_point = state["outline"][state["step_index"]]
    # ---------------------------------------------------------------------
    # 1пёЏвѓЈ Tavily search (single call)
    # ---------------------------------------------------------------------
    tavily_key = os.getenv("TAVILY_API_KEY")
    if not tavily_key:
        raise RuntimeError(
            "TAVILY_API_KEY not found in environment. Please add it to .env or export it."
        )
    search_tool = TavilySearchResults(k=5)  # returns up to 5 results
    search_results = search_tool.invoke({"query": current_point})
    if not isinstance(search_results, list) or len(search_results) == 0:
        raise RuntimeError(f"Tavily returned no results for query: '{current_point}'.")

    # Concatenate snippets for summarisation.
    snippets = []
    for r in search_results:
        # Each result is a dict; we try to pull a useful text field.
        content = r.get("content") or r.get("snippet") or r.get("title") or ""
        if content:
            snippets.append(content)
    combined = "\n\n".join(snippets[:5])  # limit size

    # ---------------------------------------------------------------------
    # 2пёЏвѓЈ Summarise with LLM
    # ---------------------------------------------------------------------
    llm = get_llm()
    summarise_prompt = (
        f"You are summarising web search results for a research brief. Using the information "
        f"below, write a concise note (5вЂ‘8 sentences) that explains the following point:"
        f"\n\n{current_point}\n\n"
        f"Results:\n{combined}\n\n"
        "Do NOT fabricate information; only use what is present in the results."
    )
    note = llm.invoke([HumanMessage(content=summarise_prompt)]).content.strip()

    # Update state
    new_notes = state["notes"] + [note]
    return {"notes": new_notes, "step_index": state["step_index"] + 1}


def synthesize_node(state: BriefState) -> dict:
    """Combine all notes into a coherent brief.

    The LLM receives the list of notes and the original outline and is asked to produce a
    short (ВЅвЂ‘1 page) research brief with clear headings.
    """
    if not state["notes"]:
        raise RuntimeError("No notes to synthesize.")
    llm = get_llm()
    outline_str = "\n".join([f"- {item}" for item in state["outline"]])
    notes_str = "\n\n".join(state["notes"])
    prompt = (
        "You are an academic writer. Using the outline and the collected notes, write a short "
        "research brief (about half a page to one page). The brief should be wellвЂ‘structured, "
        "include headings that correspond to the outline items, and only contain facts that "
        "appear in the notes. Do not add invented information.\n\n"
        f"Outline:\n{outline_str}\n\nNotes:\n{notes_str}\n\nBrief:"
    )
    brief = llm.invoke([HumanMessage(content=prompt)]).content.strip()
    return {"final_brief": brief}

# ---------------------------------------------------------------------------
# Build the graph
# ---------------------------------------------------------------------------
def build_graph() -> StateGraph:
    graph = StateGraph(BriefState)
    graph.add_node("outline", outline_node)
    graph.add_node("research_step", research_step_node)
    graph.add_node("synthesize", synthesize_node)

    graph.set_entry_point("outline")
    graph.add_edge("outline", "research_step")

    # Conditional loop: if more steps remain -> research_step, else -> synthesize
    def next_edge(state: BriefState) -> str:
        if state["step_index"] < len(state["outline"] or []):
            return "research_step"
        return "synthesize"

    graph.add_conditional_edges(
        "research_step",
        next_edge,
        {"research_step": "research_step", "synthesize": "synthesize"},
    )
    graph.add_edge("synthesize", END)
    return graph.compile()

# ---------------------------------------------------------------------------
# Demo / CLI entry point
# ---------------------------------------------------------------------------
def main() -> None:
    default_topic = "РљР°Рє СЃС‚СѓРґРµРЅС‚Сѓ Р±РµР·РѕРїР°СЃРЅРѕ РїРѕРґРєР»СЋС‡Р°С‚СЊ MCP Рє LangChain"
    topic = sys.argv[1] if len(sys.argv) > 1 else default_topic

    initial_state: BriefState = {
        "topic": topic,
        "outline": None,
        "step_index": 0,
        "notes": [],
        "final_brief": None,
    }

    graph = build_graph()
    try:
        final_state = graph.invoke(initial_state)
    except Exception as exc:
        print(f"\nвќЊ Execution failed: {exc}")
        sys.exit(1)

    # ---------------------------------------------------------------------
    # Pretty printing of results
    # ---------------------------------------------------------------------
    print("\n=== Generated Outline ===")
    for i, item in enumerate(final_state["outline"] or [], start=1):
        print(f"{i}. {item}")

    print("\n=== Research Steps ===")
    for i, note in enumerate(final_state["notes"]):
        print(f"[Step {i + 1}] {note}\n")

    print("\n=== Final Brief ===")
    print(final_state.get("final_brief", "<no brief generated>"))


if __name__ == "__main__":
    main()
