from typing import TypedDict, List, Dict, Optional


class CompareState(TypedDict):
    """State model for the comparison graph.

    * ``entities`` – list of three entity names to compare.
    * ``criteria`` – list of generated comparison criteria (3‑5 items).
    * ``findings`` – mapping ``entity -> list`` where each list contains a short note
      for every criterion in the same order as ``criteria``.
    * ``current_pair`` – integer index of the next (entity, criterion) pair to process.
    * ``final_table`` – markdown table generated after all research is done.
    * ``verdict`` – final recommendation generated by the LLM.
    """

    entities: List[str]
    criteria: List[str]
    findings: Dict[str, List[str]]
    current_pair: int
    final_table: Optional[str]
    verdict: Optional[str]
