import os
import json
import sys
from typing import TypedDict, List, Literal, Optional

from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, END

# Load environment variables (e.g., OPENAI_API_KEY)
load_dotenv()

# ---------------------------------------------------------------------------
# State definition
# ---------------------------------------------------------------------------
class PlanningState(TypedDict):
    """TypedDict representing the mutable state of the graph.

    - ``task``: The original user task.
    - ``plan``: List of step descriptions generated by the planning node.
    - ``current_step``: Index of the step that is about to be executed.
    - ``results``: Accumulated textual results of each executed step.
    """

    task: str
    plan: Optional[List[str]]
    current_step: int
    results: List[str]

# ---------------------------------------------------------------------------
# LLM helpers
# ---------------------------------------------------------------------------
def get_llm() -> ChatOpenAI:
    """Create a ChatOpenAI instance.

    The function respects the ``OPENAI_API_KEY`` environment variable. If the
    variable is missing, the underlying library will raise a clear error.
    """
    return ChatOpenAI(model="gpt-4o-mini", temperature=0.2)

# ---------------------------------------------------------------------------
# Node implementations
# ---------------------------------------------------------------------------
def planning(state: PlanningState) -> PlanningState:
    """Generate a plan for ``state["task"]``.

    The LLM is asked to return a JSON array with 3‑6 concise step strings.
    The function parses the JSON, stores it in ``state["plan"]`` and resets
    ``current_step`` and ``results``.
    """
    llm = get_llm()
    prompt = (
        f"You are a planning assistant. Split the following task into 3‑6 concrete "
        f"steps that can be executed sequentially. Return the steps as a JSON array "
        f"of strings. Do NOT include any extra text, only the JSON array.\n\nTask: {state['task']}"
    )
    response = llm.invoke(prompt).content
    try:
        plan = json.loads(response)
        if not isinstance(plan, list) or not all(isinstance(s, str) for s in plan):
            raise ValueError
    except Exception:
        # Fallback: try to extract a numbered list
        lines = [ln.strip() for ln in response.splitlines() if ln.strip()]
        plan = []
        for ln in lines:
            # Remove leading numbers like "1. "
            if ln and (ln[0].isdigit() or ln[0] == "-"):
                # split on first dot or parenthesis
                parts = ln.lstrip("-0123456789. )").strip()
                if parts:
                    plan.append(parts)
        if not plan:
            raise RuntimeError("Failed to parse plan from LLM response.")
    # Update state
    state["plan"] = plan
    state["current_step"] = 0
    state["results"] = []
    # Print the plan for the user
    print("\nПлан:")
    for idx, step in enumerate(plan, 1):
        print(f"{idx}. {step}")
    return state

def execution(state: PlanningState) -> PlanningState:
    """Execute a single step from the plan.

    The step description is sent to the LLM, the answer is appended to ``results``
    and ``current_step`` is incremented.
    """
    if state["plan"] is None:
        raise RuntimeError("Plan is not initialized.")
    idx = state["current_step"]
    if idx >= len(state["plan"]):
        raise RuntimeError("Current step index out of range.")
    step_desc = state["plan"][idx]
    llm = get_llm()
    prompt = (
        f"You are executing the following step as part of a larger task.\n"
        f"Step {idx + 1}: {step_desc}\n"
        f"Provide a concise answer that fulfills the step."
    )
    answer = llm.invoke(prompt).content.strip()
    state["results"].append(answer)
    state["current_step"] = idx + 1
    print(f"[Шаг {idx + 1}] {answer}")
    return state

def should_continue(state: PlanningState) -> Literal["execute", "finish"]:
    """Conditional edge: continue executing or finish the graph."""
    if state["plan"] is None:
        raise RuntimeError("Plan is not set when evaluating continuation condition.")
    return "finish" if state["current_step"] >= len(state["plan"]) else "execute"

def finish(state: PlanningState) -> PlanningState:
    """Combine all step results into a final summary.

    For simplicity we concatenate the results. Optionally, we could ask the LLM
    to synthesize a summary, but concatenation keeps the example deterministic.
    """
    if not state["results"]:
        summary = "No results were generated."
    else:
        # Simple concatenation with line breaks
        summary = "\n".join(state["results"]).strip()
    print("\nИтог:")
    print(summary)
    # Store the summary back into the state for possible downstream use
    state["summary"] = summary  # type: ignore
    return state

# ---------------------------------------------------------------------------
# Graph construction
# ---------------------------------------------------------------------------
def build_graph() -> StateGraph:
    graph = StateGraph(PlanningState)
    graph.add_node("planning", planning)
    graph.add_node("execution", execution)
    graph.add_node("finish", finish)
    graph.add_conditional_edges(
        "execution",
        should_continue,
        {"execute": "execution", "finish": "finish"},
    )
    # Define the start edge
    graph.set_entry_point("planning")
    # Connect planning directly to execution
    graph.add_edge("planning", "execution")
    # Connect finish to END
    graph.add_edge("finish", END)
    return graph.compile()

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def run(task: str) -> None:
    """Run the planning agent for a given *task* string.

    The function builds the graph, creates the initial state and invokes the
    compiled graph. All intermediate output is printed to stdout.
    """
    graph = build_graph()
    initial_state: PlanningState = {
        "task": task,
        "plan": None,
        "current_step": 0,
        "results": [],
    }
    # ``invoke`` runs the graph synchronously until it reaches END.
    graph.invoke(initial_state)

# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python planning_agent.py \"<task description>\"")
        sys.exit(1)
    task_input = " ".join(sys.argv[1:])
    run(task_input)
