from typing import TypedDict, List, Optional


class AdventureState(TypedDict, total=False):
    """State carried through the LangGraph execution.

    Fields:
        theme: The initial theme supplied by the user.
        hook: Short story hook generated by the LLM.
        options: List of three possible actions for the hero.
        user_choice: The option selected by the user.
        ending: Short ending generated by the LLM after the choice.
    """

    theme: str
    hook: str
    options: List[str]
    user_choice: str
    ending: str
