from typing import TypedDict, List, Optional


class BriefState(TypedDict):
    """State model for the research‑brief workflow.

    * ``topic`` – the subject supplied by the user.
    * ``outline`` – list of 4‑5 research points generated by the LLM.
    * ``step_index`` – which outline item is currently being processed.
    * ``notes`` – accumulated short notes for each processed point.
    * ``final_brief`` – the synthesized brief produced at the end.
    """

    topic: str
    outline: Optional[List[str]]
    step_index: int
    notes: List[str]
    final_brief: Optional[str]
